### ISSUE TITLE
Intermittently thrown NoHttpResponseException

### ISSUE THREAD

**Issue by bvbsdvy** [okta/oktasdk-java#24] opened 2016-04-22 15:48 UTC
Calling the authenticate API (`AuthApiClient.authenticate(String,String,String)`), occasionally `org.apache.http.NoHttpResponseException` is thrown.

It seems one possible cause is that the persistent HTTP connections are timing out on the server side but Apache HttpClient is attempting to reuse them. Although there may be several ways to fix that, if it is in fact the underlying cause, we have not been able to consistently reproduce the issue, so we cannot evaluate the effectiveness of any attempted fix.

Does anyone know a consistent way to reproduce this issue?

As a temporary workaround, we retry the call up to 3 times when a `NoHttpResponseException` occurs and this seems to have suppressed the problem well enough for now that it does not affect our users at least.

Looks like someone may be trying to fix it here: #23 
I am interested in understanding the root cause and a way to reproduce it so we can see if any proposed fixes are working.

**Comment by ashishgupta-okta** [comment] 2016-04-22 17:00
@bvbsdvy I have been able to reproduce it consistently and I also have tested with multiple scenarios. There are sure many ways to fix it. When the server closes the connection, only the next client request fails because the client is not aware of the close, so retrying the request will work. The root cause lies in the Apache HTTPClient and not our code. Section 2.5 here explains that: https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html. As I understand it is "not 100%" reliability of the http client to detect stale connections. 

To reproduce the issue , you can make 200 requests in a loop with a delay of 6secs. The TTL on our server is 5 seconds. I have consistently been able to reproduce the issue using this.

**Comment by ashishgupta-okta** [comment] 2016-04-22 17:25
Also , this issue is not just with AuthApiClient , this issue happens  with any API if we use the Apache HTTPClient.

**Comment by bvbsdvy** [comment] 2016-04-22 19:10
I was not able to reproduce it with the following code. All 200 tries were successful:

    public void testOkta() throws Exception {
        ApiClientConfiguration config = new ApiClientConfiguration(oktaUrl, oktaApiKey);
        AuthApiClient apiClient = new AuthApiClient(config);

        for (int i = 0; i < 200; i++) {
            AuthResult result = apiClient.authenticate(username, password, "");
            System.out.println(i + ". " + result.getStatus());
            Thread.sleep(6000);
        }
    }

(`oktaUrl`, `oktaApiKey`, `username`, and `password` are just Strings defined in my test class.)

I tried one run using HttpClient 4.5.2 with HttpCore 4.4.4 -- these are the latest versions of the Apache libraries currently. I also tried a second run using the default versions that are dependencies of the Okta SDK: HttpClient 4.3.6.

The version of Okta SDK I'm using is 874dcfdc82b70a77c8a7d694c23ff99fcd8d8f28.

**Comment by ashishgupta-okta** [comment] 2016-04-22 19:22
Try this 
` for(int i = 0 ; i < 500; i++) {
            List<User> users = usersClient.getUsersWithQuery(Integer.toString(random.nextInt()));
            Thread.sleep(6000);
            System.out.println(i);
            User newUser = usersClient.createUser(
                    "First",
                    "Last",
                    "login" + Integer.toString(random.nextInt()) + "@example.com",
                    "email" + Integer.toString(random.nextInt()) + "@example.com",
                    true);

            List<UserGroup> userGroups = userGroupApiClient.getUserGroupsWithLimit(1);

            // Read
            User user = usersClient.getUser(newUser.getId());
            Assert.assertTrue(newUser.getId().equals(user.getId()));

            // Update
            user.getProfile().setLastName("NewLast");
            user = usersClient.updateUser(user);

            usersClient.setRecoveryQuestion(newUser.getId(), "how are you", "winter is coming");

            UserGroup group = new UserGroup();
            group.setId(Integer.toString(random.nextInt()));
            UserGroupProfile profile = new UserGroupProfile();
            profile.setName(Integer.toString(random.nextInt()));
            group.setProfile(profile);

            group = userGroupApiClient.createUserGroup(group);

            userGroupApiClient.addUserToGroup(group.getId(), newUser.getId());
        }`

**Comment by lboyette-okta** [comment] 2016-11-18 23:07
This should be fixed by https://github.com/okta/oktasdk-java/pull/23

**Closed by lboyette-okta** 2016-11-18 23:07 UTC

**Comment by ggehlot** [comment] 2017-08-16 01:09
@lboyette-okta In the commit, I see that you are using StandardHttpRequestRetryHandler to fix this issue. But AuthApiClient.authenticate method uses POST method which is not idempotent. But I think StandardHttpRequestRetryHandler only retries idempotent methods. So that excludes POST which is used in this method. Can you please explain how the fix works in this case?

**Comment by lboyette-okta** [comment] 2017-08-16 20:46
@ggehlot You're correct that StandardHttpRequestRetryHandler doesn't cover that case, so the current fix won't work for the AuthApiClient (or for any methods that require POST).
